version: "3.4"

services:
  rust_db:
    image: mysql:latest
    container_name: rust_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "rootx"
    restart: always
    volumes:
      - rust_dbdata:/var/lib/mysql
    networks:
      - rust_network

volumes:
  rust_dbdata:

networks:
  rust_network:
    driver: bridge
    name: rust_network
