version: "3.4"

services:
  rust_db:
    image: mysql:latest
    container_name: rust_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "rootx"
    restart: always
    volumes:
      - rust_dbdata:/var/lib/mysql
    networks:
      - rust_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootx"]
      interval: 30s 
      retries: 3 
      start_period: 10s
      timeout: 10s

  rust_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: rust_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: rust_db
      PMA_USER: root
      PMA_PASSWORD: "rootx"
      UPLOAD_LIMIT: 300M
    networks:
      - rust_network

volumes:
  rust_dbdata:
    driver: local
    name: rust_dbdata

networks:
  rust_network:
    driver: bridge
    name: rust_network
