version: '3.8'

services:
  rust_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rust_app
    container_name: rust_app
    environment:
      - DATABASE_URL=mysql://root:rootx@rust_db:3306/oriochat_user_db
      - JWT_SECRET=12ZCDSGFERT4523
    ports:
      - "5000:5000"
      - "50051:50051"
    networks:
      - rust_network

networks:
  rust_network:
    external: true