version: '3.8'

services:
  rust_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mysql://root:rootx@127.0.0.1:3306/oriochat_user_db
      - JWT_SECRET=12ZCDSGFERT4523
    ports:
      - "5000:5000"
    networks:
      - rust_shared_network

networks:
  rust_shared_network:
    driver: bridge
