version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rust_app
    environment:
      DATABASE_URL: mysql://root:root@root@rust_mysql_db:3306/oriochat_user_db
    ports:
      - "5000:5000"
    networks:
      - rust_app_network

networks:
  rust_app_network:
    external: true
